### ISSUE TITLE
Petshop tutorial problem

### ISSUE THREAD

**Issue by sgehrman** [trufflesuite/trufflesuite.com#13] opened 2017-11-05 22:17 UTC
Not sure if it was something I did, but I got to the end of the petshop demo and ran it and all the pets were marked adopted and had the success button.  I was unable to adopt.

**Comment by bmmpxf** [comment] 2017-11-08 20:18
Hi @sgehrman . Sorry you're having problems. In order for us to troubleshoot, we'd need to know a bit more information on how to reproduce the issue. Since the tutorial involves editing text files, we'd want to see yours to make sure there are no syntax errors. Also, did you encounter any other issues along the way? Did all of the tests run?

We just did an update of the tutorial, so I've tested it fairly recently, though of course errors can happen. Make sure you're using the most recent version of Truffle (4.0.1 as of this moment) as that was the version we tested with most recently.

**Comment by carlzoo** [comment] 2017-11-11 21:14
I also am not clear where to get 100 ethers to run the contract. When I created account on metamask I have 0 ethers.

**Comment by bmmpxf** [comment] 2017-11-13 16:47
@carlzoo Make sure that Metamask is connected to the right network. Also, make sure that the account you're looking at in MetaMask is the same account as the first account listed when you first ran Truffle Develop. Only that account should have the 100 ether.

If you need more assistance, please check out our [Gitter](https://gitter.im/ConsenSys/truffle). The community is here to help!

**Comment by imshubhamsingh** [comment] 2017-11-22 01:16
@sgehrman and @carlzoo I also faced the same problem few hours ago. I didn't run truffle migrate just before starting the dApp. Migrations are JavaScript files that help you deploy contracts to the Ethereum network. If you didn't complete the tutorial in one go, you need to run `truffle develop` command and then `truffle(develop)> migrate` again. It solved my problem.

**Comment by bmmpxf** [comment] 2017-11-27 19:46
Hi @sgehrman . I'm going to close this issue, but if you're still having problems, please feel free to reopen and provide us with more information on how to reproduce your experience. Thanks!

**Closed by bmmpxf** 2017-11-27 19:46 UTC

**Comment by MrThiago** [comment] 2017-12-14 07:52
Hello guys. I am having the same issue.
i already have my personal Meta Mask Account.

How to get the 100ETH for the dev account ?

**Comment by imshubhamsingh** [comment] 2017-12-14 21:58
Just add a new custom rpc with the url as seen on truffle develop and switch to that network

**Comment by MrThiago** [comment] 2017-12-15 00:13
I did that.
The demo works. But I can’t test the adoption because there is no ETH In the custom rcp

**Comment by imshubhamsingh** [comment] 2017-12-15 00:23
Ok, now there is only one thing that comes to my mind, remove metamask and install it again. But this time use Import Existing DEN. Then put in Mnemonic as provided by truffle. After that use custom rpc. I think now it should work.

**Comment by HGBG** [comment] 2018-03-13 22:18
nor reset, from the settings menu, nor reinstall did work for me. I have eth in my wallet to run the transaction but metamask is simply not opening when the button "adopt" is pressed. Any extra advice?

**Comment by BeFiveINFO** [comment] 2018-03-20 16:46
@HGBG and others

Try:

* Make sure that your Ganash is launched and working properly.
* Find your MNEMONIC. That appears in the most visible part in the Ganash front end UI.

1. Logout MetaMask
2. Open the little window by clicking on the foxy icon, Find a link that reads "Restore from seed phrase".
3. Copy and Paste the MNEMONIC into Wallet Seed text field. 
4. Enter your password and login to MetaMask.

You should now find an account with the promised 100 ETH credited to your test account.

Good luck.

**Comment by blacar** [comment] 2018-03-29 14:14
Same issue as @HGBG , nothing is happening when we click on the "adopt" button.
Also nothing appear at chrome console.

**Comment by pbrudny** [comment] 2018-04-15 19:51
Thank You @BeFiveINFO This helped me a lot. 
Now is see that the problem occurs when using both `Ganache` and `truffle develop` and mixing ports and their mnemonics. It's actually mentioned in the note: 
```
Note: If you are developing in an environment without a graphical interface, 
you can also use Truffle Develop, Truffle's built-in personal blockchain, instead of Ganache. 
You will need to change some settings—such as the port the blockchain 
runs on—to adapt the tutorial for Truffle Develop.
```

**Comment by sheela39** [comment] 2018-05-10 04:32
Sir, the program works fine for me, but will someone be able to explain the transactions in the metamask 
![image](https://user-images.githubusercontent.com/38527054/39852265-2e29fd92-5439-11e8-8a23-8d8241a03d6e.png)

**Comment by sheela39** [comment] 2018-05-10 04:34
what does this transaction mean, I have the date, timestamp, my account1 address and receiver address, now why the 0 ETH shows

**Comment by bitbutter** [comment] 2018-06-25 11:21
Same issue as @HGBG. Following the pet store tutorial all works as expected until clicking any 'Adopt' button on the web page. There's no response from the app. (Metamask balances show up as expected).

**Comment by HankHoneymoon** [comment] 2021-05-21 13:09
TO GET 100 ETH (as the tutorial completely skips that part) just connect to the local network (as described in the tutorial) then go your instance of Ganache. Next to the first transaction, the one with less than 100 eth, click the key to copy the private key. Then go to Import Account in Metamask (in your local/ganache network that you just created) and paste that into the private key field. You'll then have imported the Ganache account into your Metamask wallet on the local Ganache network.

**Comment by HankHoneymoon** [comment] 2021-05-21 13:44
BTW I was able to get it to work by simply switching accounts to a different account, then back to my Test account (I set up a completely separate wallet for testing, of course, but might work if you just start a new wallet and switch between them as well.)

Not sure what the problem was, but the tutorial is finished, so moving on.
