### ISSUE TITLE
Assert.equal not running even with 'truffle unbox' project 

### ISSUE THREAD

**Issue by zak100** [trufflesuite/trufflesuite.com#728] opened 2020-07-15 23:36 UTC
I ran the pet shop project. It uses "truffle unbox". The petshop project  at:

https://www.trufflesuite.com/tutorials/pet-shop

is able to execute 'Assert.equal' command but when I am using Assert.equal, I am getting error. I am first deploying the pet-shop project in my project folder using "truffle unbox petshop". It creates the files but then I modified the files as follows. My files are:
//Funding.sol

pragma solidity 0.5.16;
contract Funding {
   address public owner;
   constructor() public {
      owner = msg.sender;
   }
}

//2_deploy_contracts.js
var Funding= artifacts.require("Funding");
module.exports = function(deployer){
   deployer.deploy(Funding);
};
//TestFunding.sol
pragma solidity ^0.5.0;
import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/Funding.sol";

contract  TestFunding{

  function testSettingAnOwnerDuringCreation() public {
    Funding funding = new Funding();
    Assert.equal(funding.owner(), this, "An owner is different than a deployer");
  }
}
I am getting following error when I am compiling my code using "truffle test":
$ truffle test You can improve web3's peformance when running Node.js versions older than 10.5.0 by installing the (deprecated) scrypt package in your project Using network 'development'.
Compiling your contracts... ===========================
Compiling ./test/TestFunding.sol
/home/zulfi/Truffle programs/michal-unbox2/test/TestFunding.sol:10:5: TypeError: Member "equal" not found or not visible after argument-dependent lookup in type(library Assert). Assert.equal(funding.owner(), this, "An owner is different than a deployer"); ^----------^
Compilation failed. See above. Truffle v5.1.33 (core: 5.1.33) Node v8.10.0
Somebody please guide me how can I modify the pet-shop project to create a new project for testing so that it can use Assert.equal(...)command.
Zulfi.

**Comment by zak100** [comment] 2020-07-15 23:43
Please contact me through:
zulfi6000@yahoo.com

**Comment by DiscRiskandBisque** [comment] 2020-08-14 19:21
Hi @zak100, though this isn't related to our Pet Shop box, I'll take a shot at debugging here: looks like the test is working as intended: `funding.owner()` will be the deployer address and `this` in that context will be the contract address, so I would not expect them to be equal. Correct me if I'm wrong?

**Comment by DiscRiskandBisque** [comment] 2020-09-25 19:15
Closing for now, if this is still an issue @zak100 please re-open--thanks!

**Closed by DiscRiskandBisque** 2020-09-25 19:15 UTC
