### ISSUE TITLE
Pet-Shop Tutorial truffle test error 

### ISSUE THREAD

**Issue by Aliasgharmohammad** [trufflesuite/trufflesuite.com#102] opened 2018-04-07 10:51 UTC
**hi i have been following pet-shop-tutorial and when i run truffle test I face with following error 
thanks in advance** 

Error parsing C:\pet-shop-tutorial\test\TestAdoption.sol: ParsedContract.sol:14:5: ParserError: Expected pragma, import
directive or contract/interface/library definition.
    function testUserCanAdoptPet() public {
    ^

Using network 'development'.

Compiling .\contracts\Adoption.sol...
Compiling .\test\TestAdoption.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

Compilation warnings encountered:

truffle/Assert.sol:1563:9: Warning: Use of the "var" keyword is deprecated.
        var nstr = _itoa(value, 10);
        ^------^
,truffle/Assert.sol:1580:9: Warning: Use of the "var" keyword is deprecated.
        var nstr = _utoa(value, 10);
        ^------^
,truffle/Assert.sol:1597:9: Warning: Use of the "var" keyword is deprecated.
        var nstr = _ltoa(value);
        ^------^
,truffle/Assert.sol:1347:13: Warning: Invoking events without "emit" prefix is deprecated.
            TestEvent(true, "");
            ^-----------------^
,truffle/Assert.sol:1349:13: Warning: Invoking events without "emit" prefix is deprecated.
            TestEvent(false, message);
            ^-----------------------^

  TestAdoption
    1) "before all" hook: prepare suite

  0 passing (2s)
  1 failing

  1) TestAdoption "before all" hook: prepare suite:
     Error: Could not find artifacts for /C/pet-shop-tutorial/contracts/Adoption.sol from any sources
      at Resolver.require (C:\Users\Ali\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-resolver\index
.js:37:1)
      at TestResolver.require (C:\Users\Ali\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-core\lib\t
esting\testresolver.js:17:1)
      at TestResolver.require (C:\Users\Ali\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-core\lib\t
esting\testresolver.js:17:1)
      at C:\Users\Ali\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-core\lib\testing\soliditytest.js
:141:1
      at Array.forEach (<anonymous>)
      at C:\Users\Ali\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-core\lib\testing\soliditytest.js
:140:1
      at C:\Users\Ali\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-deployer\src\deferredchain.js:20
:1
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by minzhenye** [comment] 2018-04-08 09:54
Hi, I encountered same problem. Have you found the reason?

**Comment by Aliasgharmohammad** [comment] 2018-04-12 07:29
hi not yet  I hope someone can help
ok what do you think is the problem
i will try and if you find please share

**Comment by Aliasgharmohammad** [comment] 2018-04-12 10:09
Hi Thanks Allah I found the answer according to beloved Travis Rivera on StackExchange the problem relates to the version of truffle we use here the solutoin copyed from his answear 

There is something wrong with the latest truffle version. To solve this problem I had to do the following things to find a truffle version that worked.

First check for available versions of truffle with the following command.

npm view truffle versions
Then for each item on the list starting from the latest version. I uninstalled truffle with

npm uninstall -g truffle
then installed the next oldest version with

npm install -g truffle@<version#>
then deleted the build folder

then compiled the project with

truffle compile
then ran

truffle test
if this fails move on to the next oldest version and repeat the test.

In my case a working version of truffle was 4.1.4

**Comment by Aliasgharmohammad** [comment] 2018-04-12 10:14
the way you specify the version you intend to download is such this##  npm install -g truffle@4.1.4

**Comment by bmmpxf** [comment] 2018-04-16 18:26
Hi there. Thanks for the report. I'll take a look at the tutorial against the latest version of Truffle and see if I can reproduce it here.

**Comment by Aliasgharmohammad** [comment] 2018-04-28 12:28
HI thanks man

**Comment by OrangePartisan** [comment] 2018-12-09 12:49
It's not the version of truffle, it's a mismatch of the parenthesis. I found the following on stackoverflow:

https://stackoverflow.com/questions/49090043/truffle-compile-failing-parsererror-expected-token-lparen-got-identifier-funct

So you should check the syntaxis of the TestAdoption file you made. I work on the latest version and my test worked fine.

**Comment by DiscRiskandBisque** [comment] 2019-12-16 21:24
Hey @Aliasgharmohammad! Sorry for the extremely late reply. I'm closing this due to its age, and the fact that the Pet Shop tutorial has gone through a few iterations since 2018. If this issue persists please re-open, thanks!

**Closed by DiscRiskandBisque** 2019-12-16 21:24 UTC
