### ISSUE TITLE
Tutorials link at the bottom of the quickstart page is broken landing to a 404

### ISSUE THREAD

**Issue by ericnordelo** [trufflesuite/trufflesuite.com#1000] opened 2021-06-11 21:32 UTC
https://www.trufflesuite.com/docs/truffle/quickstart

**Comment by haltman-at** [comment] 2021-06-15 03:12
This seems to be fixed now?

**Comment by kevinbluer** [comment] 2021-06-16 18:14
Confirmed that this is fixed. Closing 👌

**Closed by kevinbluer** 2021-06-16 18:14 UTC
